// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByp89MtvL6cXkrEk1amx7Tqfa8wNObV6I',
    appId: '1:181392368151:web:21bd76aca78f19123d3252',
    messagingSenderId: '181392368151',
    projectId: 'laptop-harbor-50868',
    authDomain: 'laptop-harbor-50868.firebaseapp.com',
    storageBucket: 'laptop-harbor-50868.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBis7pqaTMBgx_JF3fdD1QKPOEu0NeVelI',
    appId: '1:181392368151:android:fb07825835d1257f3d3252',
    messagingSenderId: '181392368151',
    projectId: 'laptop-harbor-50868',
    storageBucket: 'laptop-harbor-50868.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjWLk3BRZK8WTBk6j34uyQlb0-yS0HxCQ',
    appId: '1:181392368151:ios:012e862bfbf4efc73d3252',
    messagingSenderId: '181392368151',
    projectId: 'laptop-harbor-50868',
    storageBucket: 'laptop-harbor-50868.appspot.com',
    androidClientId: '181392368151-glike24p73mi3lob4h2fj68bbg7vbcn8.apps.googleusercontent.com',
    iosClientId: '181392368151-gsevkclir92d04c41aubdslm52etie3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.lhstore',
  );
}
